spring.application.name=auto-salon

spring.datasource.url=jdbc:postgresql://localhost:5436/postgres
spring.datasource.username=postgres
spring.datasource.password=1111

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret-key=uxBx3ron5oXRemmougxpydAfAPJMfIZjt7Kc4fBFRgZ
jwt.lifetime=86400000